// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $('#hero li a').click(function() {
      $('#hero li').removeClass('selected');
      $(this).parent().addClass('selected');
      return false;
    });
  });

}).call(this);
